all:
  vars:
    ansible_user: roswellcity
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_manet
    wifi_interface: wlan0

  hosts:
    rpi4-3:
      ansible_host: 192.168.40.3
      manet_ip: 172.0.10.3
    rpi5-2:
      ansible_host: 192.168.40.2
      manet_ip: 172.0.10.2
    rpi5-1:
      ansible_host: 192.168.40.1
      manet_ip: 172.0.10.1

  children:
    manet_nodes:
      hosts:
        rpi4-3:
        rpi5-1:
        rpi5-2:

    ethernet_node:
      hosts:
        rpi5-1:
