all:
  vars:
    ansible_user: roswellcity
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_manet
    adhoc_ssid: "rpi-adhoc"             # SSID for the IBSS network
    adhoc_freq: "2412"                  # Frequency in MHz (2412 MHz = channel 1, 2.4 GHz)
    batman_interface: "bat0"            # Name of the batman-adv virtual interface
    manet_netmask: "24"                 # Netmask bit

  hosts:
    rpi5-1:
      ansible_host: 192.168.40.1
      manet_ip: 172.0.10.1
    rpi5-2:
      ansible_host: 192.168.40.2
      manet_ip: 172.0.10.2
    rpi4-3:
      ansible_host: 192.168.40.3
      manet_ip: 172.0.10.3
    rpi2w-4:
      ansible_host: 192.168.40.4
      manet_ip: 172.0.10.4

  children:
    manet_nodes:
      hosts:
        rpi4-3:
        rpi5-1:
        rpi5-2:
        rpi2w-4:

    visualization_node:
      hosts:
        rpi5-1:
