all:
  hosts:
    rpi4-1:
      ansible_host: 192.168.40.3
      ansible_user: roswellcity
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_manet
      manet-ip: 172.0.10.3
    rpi5-2:
      ansible_host: 192.168.40.2
      ansible_user: roswellcity
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_manet
      manet-ip: 172.0.10.2
    rpi5-1:
      ansible_host: 192.168.40.1
      ansible_user: roswellcity
      ansible_ssh_private_key_file: ~/.ssh/id_rsa_manet
      manet-ip: 172.0.10.1

  children:
    manet_nodes:
      hosts:
        rpi4:
        rpi5-1:
        rpi5-2:

    ethernet_node:
      hosts:
        rpi5-2: