---
- name: Setup Raspberry Pi MANET Network
  hosts: manet_nodes
  become: yes
  gather_facts: yes
  vars:
    manet_ip: "{{ hostvars[inventory_hostname]['manet-ip'] }}"
    wifi_interface: "{{ hostvars[inventory_hostname]['wifi_interface'] }}"
    network_name: "MANET-NET"
    frequency: "2412"
    batman_interface: "bat0"

  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    # - name: Reboot the device
    #   reboot:
    #     msg: "Rebooting to apply updates..."
    #     pre_reboot_delay: 5
    #     post_reboot_delay: 15
    #     test_command: "whoami"

    # - name: Wait for device to come back online
    #   wait_for_connection:
    #     delay: 10
    #     timeout: 120

    - name: Install required packages
      apt:
        name:
          - batctl
          - iw
          - net-tools
          - avahi-daemon
          - avahi-utils
        state: present

    - name: Check detected wireless interface
      shell: iw dev | grep Interface | awk '{print $2}'
      register: detected_interface
      changed_when: false

    - name: Validate wireless interface with inventory value
      fail:
        msg: "Mismatch! Inventory interface '{{ wifi_interface }}' does not match detected interface '{{ detected_interface.stdout }}'"
      when: detected_interface.stdout != wifi_interface

    - name: Debug detected and inventory interface
      debug:
        msg: "Inventory interface: {{ wifi_interface }}, Detected interface: {{ detected_interface.stdout }}"

    - name: Disable and set wireless interface to IBSS mode (Ad-Hoc)
      shell: |
        ip link set {{ wifi_interface }} down
        iw dev {{ wifi_interface }} set type ibss
        ip link set {{ wifi_interface }} up

    - name: Create Ad Hoc network
      shell: iw dev {{ wifi_interface }} ibss join "{{ network_name }}" {{ frequency }}

    - name: Verify network mode
      shell: iw dev
      register: iw_dev_output
    - debug:
        msg: "{{ iw_dev_output.stdout_lines }}"

    - name: Load BATMAN-ADV kernel module
      modprobe:
        name: batman-adv
        state: present

    - name: Ensure BATMAN-ADV module loads on boot
      lineinfile:
        path: /etc/modules
        line: "batman-adv"
        state: present

    - name: Configure BATMAN-ADV networking
      shell: |
        ip link set {{ wifi_interface }} mtu 1500
        batctl if add {{ wifi_interface }}
        ip link set {{ batman_interface }} up

    - name: Check if IP is already assigned to bat0
      shell: ip addr show dev bat0 | grep "{{ manet_ip }}"
      register: ip_check
      changed_when: false
      ignore_errors: yes  # Allow task to continue even if grep fails

    - name: Assign static IP to bat0 (if not assigned)
      shell: ip addr add {{ manet_ip }}/24 dev bat0
      when: ip_check.rc != 0  # Only assign if IP is NOT already assigned

    - name: Verify MANET network
      shell: batctl n
      register: batctl_n_output
    - debug:
        msg: "{{ batctl_n_output.stdout_lines }}"

    - name: Configure Avahi daemon
      template:
        src: avahi-daemon.conf.j2
        dest: /etc/avahi/avahi-daemon.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart Avahi

    - name: Enable and start Avahi service
      systemd:
        name: avahi-daemon
        enabled: yes
        state: started

    - name: Ensure /etc/network/interfaces.d directory exists
      file:
        path: /etc/network/interfaces.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create adhoc-mesh file if it doesn't exist
      copy:
        content: ""
        dest: /etc/network/interfaces.d/adhoc-mesh
        force: no
        owner: root
        group: root
        mode: "0644"

    - name: Make network settings persistent
      template:
        src: adhoc-mesh.j2
        dest: /etc/network/interfaces.d/adhoc-mesh
        owner: root
        group: root
        mode: "0644"

    - name: Set script permissions
      file:
        path: /etc/network/interfaces.d/adhoc-mesh
        mode: "0755"

    # - name: Reboot the device after configuration
    #   reboot:
    #     msg: "Rebooting after MANET setup..."
    #     pre_reboot_delay: 5
    #     post_reboot_delay: 15
    #     test_command: "whoami"

    # - name: Wait for device to come back online
    #   wait_for_connection:
    #     delay: 10
    #     timeout: 120

    - name: Verify BATMAN-ADV neighbors
      shell: batctl n
      register: batctl_neighbors
    - debug:
        msg: "Neighbors:\n{{ batctl_neighbors.stdout_lines }}"

    - name: Verify BATMAN-ADV routing table
      shell: batctl o
      register: batctl_routes
    - debug:
        msg: "Routing Table:\n{{ batctl_routes.stdout_lines }}"

    - name: Ping all other nodes to verify connectivity
      shell: "ping -c 3 {{ item }}"
      with_items:
        - "{{ groups['manet_nodes'] | map('extract', hostvars, 'manet_ip') | list | difference([manet_ip]) }}"
      register: ping_results
      ignore_errors: yes

    - name: Display ping results
      debug:
        msg: "{{ ping_results.results | map(attribute='stdout_lines') | list }}"

  handlers:
    - name: Reload systemctl and Restart Avahi
      block:
        - name: Reload systemctl daemon
          shell: systemctl daemon-reload

        - name: Restart Avahi
          systemd:
            name: avahi-daemon
            state: restarted
