---
- name: Configure Network Interface for IBSS Mode
  hosts: manet_nodes
  become: true
  vars:
    wifi_interface: "{{ hostvars[inventory_hostname]['wifi_interface'] }}"
    network_name: "MANET-NET"
    frequency: "2412"

  tasks:
    - name: Set Wi-Fi interface to Ad-Hoc mode
      block:
        - name: Disable interface
          command: ip link set {{ wifi_interface }} down

        - name: Set interface mode to IBSS
          command: iw dev {{ wifi_interface }} set type ibss

        - name: Enable interface
          command: ip link set {{ wifi_interface }} up

        - name: Join Ad-Hoc network
          command: iw dev {{ wifi_interface }} ibss join "{{ network_name }}" {{ frequency }}

      tags: network
