---
- name: Configure Avahi for Service Discovery
  hosts: manet_nodes
  become: true

  tasks:
    - name: Deploy Avahi configuration
      template:
        src: avahi-daemon.conf.j2
        dest: /etc/avahi/avahi-daemon.conf
        owner: root
        group: root
        mode: "0644"
      notify: Restart Avahi

    - name: Enable and start Avahi service
      systemd:
        name: avahi-daemon
        enabled: yes
        state: started

  handlers:
    - name: Restart Avahi
      systemd:
        name: avahi-daemon
        state: restarted
