---
- name: Verify MANET Connectivity
  hosts: manet_nodes
  become: true
  vars:
    manet_ip: "{{ hostvars[inventory_hostname]['manet-ip'] }}"

  tasks:
    - name: Check BATMAN-ADV neighbors
      command: batctl n
      register: batctl_neighbors
      changed_when: false

    - name: Check BATMAN-ADV routing table
      command: batctl o
      register: batctl_routes
      changed_when: false

    - name: Display BATMAN-ADV neighbors
      debug:
        var: batctl_neighbors.stdout_lines

    - name: Display BATMAN-ADV routing table
      debug:
        var: batctl_routes.stdout_lines

    - name: Ping all other nodes
      shell: "ping -c 3 {{ item }}"
      with_items:
        - "{{ groups['manet_nodes'] | map('extract', hostvars, 'manet_ip') | list | difference([manet_ip]) }}"
      register: ping_results
      ignore_errors: true

    - name: Display ping results
      debug:
        msg: "{{ ping_results.results | map(attribute='stdout_lines') | list }}"
